/* tslint:disable */
/* eslint-disable */
/**
 * skoop/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1Hello } from './V1Hello';
import {
    V1HelloFromJSON,
    V1HelloFromJSONTyped,
    V1HelloToJSON,
} from './V1Hello';

/**
 * 
 * @export
 * @interface V1Hellos
 */
export interface V1Hellos {
    /**
     * 
     * @type {Array<V1Hello>}
     * @memberof V1Hellos
     */
    hellos?: Array<V1Hello>;
}

/**
 * Check if a given object implements the V1Hellos interface.
 */
export function instanceOfV1Hellos(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1HellosFromJSON(json: any): V1Hellos {
    return V1HellosFromJSONTyped(json, false);
}

export function V1HellosFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Hellos {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hellos': !exists(json, 'hellos') ? undefined : ((json['hellos'] as Array<any>).map(V1HelloFromJSON)),
    };
}

export function V1HellosToJSON(value?: V1Hellos | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hellos': value.hellos === undefined ? undefined : ((value.hellos as Array<any>).map(V1HelloToJSON)),
    };
}

