/* tslint:disable */
/* eslint-disable */
/**
 * skoop/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1Hello } from './V1Hello';
import {
    V1HelloFromJSON,
    V1HelloFromJSONTyped,
    V1HelloToJSON,
} from './V1Hello';

/**
 * 
 * @export
 * @interface V1UpsertHellosRequest
 */
export interface V1UpsertHellosRequest {
    /**
     * 
     * @type {Array<V1Hello>}
     * @memberof V1UpsertHellosRequest
     */
    hellos?: Array<V1Hello>;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1UpsertHellosRequest
     */
    fields?: Array<string>;
}

/**
 * Check if a given object implements the V1UpsertHellosRequest interface.
 */
export function instanceOfV1UpsertHellosRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1UpsertHellosRequestFromJSON(json: any): V1UpsertHellosRequest {
    return V1UpsertHellosRequestFromJSONTyped(json, false);
}

export function V1UpsertHellosRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UpsertHellosRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hellos': !exists(json, 'hellos') ? undefined : ((json['hellos'] as Array<any>).map(V1HelloFromJSON)),
        'fields': !exists(json, 'fields') ? undefined : json['fields'],
    };
}

export function V1UpsertHellosRequestToJSON(value?: V1UpsertHellosRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hellos': value.hellos === undefined ? undefined : ((value.hellos as Array<any>).map(V1HelloToJSON)),
        'fields': value.fields,
    };
}

