name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'main.go'
      - 'cmd/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
      - 'helm_chart/**'
jobs:
  release:
    name: Release chart
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.AUTOMATION_PAT }}
        fetch-depth: 0
    - name: setup git config
      run: |
        git config --global user.name "MauzaEng"
        git config --global user.email "<engineering@mauza.net>"
    - name: Get semver-tags
      run: |
        wget -c https://github.com/catalystsquad/semver-tags/releases/download/v0.3.3/semver-tags.tar.gz -O - | tar -xz
    - name: Semver Tags Run
      id: semver-tags
      run: |
        bash ./.github/scripts/do-chart-release.sh fullrun . helm_chart
    - if: steps.semver-tags.outputs.RELEASED_CHANGES == 'true'
      name: Build and push image to quay.io
      uses: catalystsquad/action-build-push-image-quay@v1
      with:
        checkout: false
        tag-versions: latest,${{ steps.semver-tags.outputs.NEW_VERSION }}
        username: ${{ secrets.QUAY_DOCKER_REGISTRY_USER }}
        password: ${{ secrets.QUAY_DOCKER_REGISTRY_PASSWORD }}
    - if: steps.semver-tags.outputs.RELEASED_CHANGES == 'true'
      name: Checkout Chart repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.AUTOMATION_PAT }}
        repository: mauza/charts
        path: chart-repository
    - if: steps.semver-tags.outputs.RELEASED_CHANGES == 'true'
      name: Upload chart to chart repository
      shell: bash
      run: |
        helm dependency update ./helm_chart
        helm package ./helm_chart -d ./chart-repository/
        cd ./chart-repository
        helm repo index .
        git add .
        git commit -m "ci: added new helm chart to repository"
        git push
